In [1]:
import pandas as pd
from pathlib import Path

path = Path("datasets/ridership/CTA_-_Ridership_-_Daily_Boarding_Totals.csv")
df = pd.read_csv(path, parse_dates=["service_date"])
df.columns = ["date", "day_type", "bus", "rail", "total"] # shorter names
df = df.sort_values("date").set_index("date")

df = df.drop("total", axis=1) # no need for total, it's just bus + rail
df = df.drop_duplicates() # remove duplicated months (2011-10 and 2014-07)

FileNotFoundError: [Errno 2] No such file or directory: 'datasets\\ridership\\CTA_-_Ridership_-_Daily_Boarding_Totals.csv'

In [2]:
df.head()

NameError: name 'df' is not defined

In [3]:
import matplotlib.pyplot as plt
df["2019-03":"2019-05"].plot(grid=True, marker=".", figsize=(8, 3.5))
plt.show()


NameError: name 'df' is not defined

In [4]:
from statsmodels.tsa.arima.model import ARIMA

origin, today = "2019-01-01", "2019-05-31"
rail_series = df.loc[origin:today]["rail"].asfreq("D")
model = ARIMA(rail_series,
 order=(1, 0, 0),
 seasonal_order=(0, 1, 1, 7))
model = model.fit()
y_pred = model.forecast() # returns 427,758.6

NameError: name 'df' is not defined

In [5]:
origin, start_date, end_date = "2019-01-01", "2019-03-01", "2019-05-31"
time_period = pd.date_range(start_date, end_date)
rail_series = df.loc[origin:end_date]["rail"].asfreq("D")
y_preds = []
for today in time_period.shift(-1):
 model = ARIMA(rail_series[origin:today], # train on data up to "today"
 order=(1, 0, 0),
 seasonal_order=(0, 1, 1, 7))
 model = model.fit() # note that we retrain the model every day!
 y_pred = model.forecast()[0]
 y_preds.append(y_pred)
y_preds = pd.Series(y_preds, index=time_period)
mae = (y_preds - rail_series[time_period]).abs().mean() # returns 32,040.7

NameError: name 'df' is not defined

In [6]:
import tensorflow as tf

my_series = [0, 1, 2, 3, 4, 5]
my_dataset = tf.keras.utils.timeseries_dataset_from_array(
 my_series,
 targets=my_series[3:], # the targets are 3 steps into the future
 sequence_length=3,
 batch_size=2
)


In [7]:
list(my_dataset)

[(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
  array([[0, 1, 2],
         [1, 2, 3]])>,
  <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4])>),
 (<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[2, 3, 4]])>,
  <tf.Tensor: shape=(1,), dtype=int32, numpy=array([5])>)]

In [8]:
model = tf.keras.Sequential([
 tf.keras.layers.SimpleRNN(1, input_shape=[None, 1])
])


c:\Users\PP\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [9]:
univar_model = tf.keras.Sequential([
 tf.keras.layers.SimpleRNN(32, input_shape=[None, 1]),
 tf.keras.layers.Dense(1) # no activation function by default
])


In [10]:
deep_model = tf.keras.Sequential([
 tf.keras.layers.SimpleRNN(32, return_sequences=True, input_shape=[None, 1]),
 tf.keras.layers.SimpleRNN(32, return_sequences=True),
 tf.keras.layers.SimpleRNN(32),
 tf.keras.layers.Dense(1)
])
