In [1]:
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs

X, y = make_blobs([...]) # make the blobs: y contains the cluster IDs, but we
 # will not use them; that's what we want to predict
k = 5
kmeans = KMeans(n_clusters=k, random_state=42)
y_pred = kmeans.fit_predict(X)

TypeError: unsupported operand type(s) for +: 'int' and 'ellipsis'

In [2]:
y_pred
y_pred is kmeans.labels_


NameError: name 'y_pred' is not defined

In [4]:
kmeans.cluster_centers_

NameError: name 'kmeans' is not defined

In [ ]:
import numpy as np
X_new = np.array([[0, 2], [3, 2], [-3, 3], [-3, 2.5]])
kmeans.predict(X_new)


NameError: name 'means' is not defined

In [6]:
kmeans.transform(X_new).round(2)

NameError: name 'kmeans' is not defined

In [7]:
good_init = np.array([[-3, 3], [-3, 2], [-3, 1], [-1, 2], [0, 2]])
kmeans = KMeans(n_clusters=5, init=good_init, n_init=1, random_state=42)
kmeans.fit(X)


NameError: name 'X' is not defined

In [9]:
kmeans.inertia_

AttributeError: 'KMeans' object has no attribute 'inertia_'

In [11]:
kmeans.score(X)


NameError: name 'X' is not defined

In [12]:
from sklearn.cluster import MiniBatchKMeans
minibatch_kmeans = MiniBatchKMeans(n_clusters=5, random_state=42)
minibatch_kmeans.fit(X)


NameError: name 'X' is not defined

In [13]:
from sklearn.metrics import silhouette_score
silhouette_score(X, kmeans.labels_)

NameError: name 'X' is not defined

In [15]:
from PIL import Image
import numpy as np

image = np.asarray(Image.open(filepath))
image.shape

NameError: name 'filepath' is not defined

In [16]:
X = image.reshape(-1, 3)
kmeans = KMeans(n_clusters=8, random_state=42).fit(X)
segmented_img = kmeans.cluster_centers_[kmeans.labels_]
segmented_img = segmented_img.reshape(image.shape)


NameError: name 'image' is not defined

In [17]:
from sklearn.datasets import load_digits
X_digits, y_digits = load_digits(return_X_y=True)
X_train, y_train = X_digits[:1400], y_digits[:1400]
X_test, y_test = X_digits[1400:], y_digits[1400:]

In [18]:
from sklearn.linear_model import LogisticRegression
n_labeled = 50
log_reg = LogisticRegression(max_iter=10_000)
log_reg.fit(X_train[:n_labeled], y_train[:n_labeled])

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,10000
,multi_class,'deprecated'


In [19]:

log_reg.score(X_test, y_test)

0.7581863979848866

In [20]:
k = 50
kmeans = KMeans(n_clusters=k, random_state=42)
X_digits_dist = kmeans.fit_transform(X_train)
representative_digit_idx = np.argmin(X_digits_dist, axis=0)
X_representative_digits = X_train[representative_digit_idx]


In [21]:
y_representative_digits = np.array([1, 3, 6, 0, 7, 9, 2, ..., 5, 1, 9, 9, 3, 7])

In [22]:
log_reg = LogisticRegression(max_iter=10_000)
log_reg.fit(X_representative_digits, y_representative_digits)
log_reg.score(X_test, y_test)

ValueError: Found input variables with inconsistent numbers of samples: [50, 14]

In [24]:
y_train_propagated = np.empty(len(X_train), dtype=np.int64)
for i in range(k):
    y_train_propagated[kmeans.labels_ == i] = y_representative_digits[i]

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'ellipsis'

In [25]:
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train_propagated)
log_reg.score(X_test, y_test)

c:\Users\PP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.0

In [26]:
percentile_closest = 99
X_cluster_dist = X_digits_dist[np.arange(len(X_train)), kmeans.labels_]
for i in range(k):
    in_cluster = (kmeans.labels_ == i)
    cluster_dist = X_cluster_dist[in_cluster]
    cutoff_distance = np.percentile(cluster_dist, percentile_closest)
    above_cutoff = (X_cluster_dist > cutoff_distance)
    X_cluster_dist[in_cluster & above_cutoff] = -1

partially_propagated = (X_cluster_dist != -1)
X_train_partially_propagated = X_train[partially_propagated]
y_train_partially_propagated = y_train_propagated[partially_propagated]

In [27]:
log_reg = LogisticRegression(max_iter=10_000)
log_reg.fit(X_train_partially_propagated, y_train_partially_propagated)
log_reg.score(X_test, y_test)


c:\Users\PP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 10000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=10000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.0025188916876574307

In [28]:
(y_train_partially_propagated == y_train[partially_propagated]).mean()

0.0014814814814814814

In [29]:
from sklearn.cluster import DBSCAN
from sklearn.datasets import make_moons
X, y = make_moons(n_samples=1000, noise=0.05)
dbscan = DBSCAN(eps=0.05, min_samples=5)
dbscan.fit(X)


,eps,0.05
,min_samples,5
,metric,'euclidean'
,metric_params,None
,algorithm,'auto'
,leaf_size,30
,p,None
,n_jobs,None


In [30]:
dbscan.labels_


array([ 0,  1,  2,  5,  6,  0,  1,  3,  0,  4,  3,  2,  5,  6, 14,  6, 11,
        1,  3,  7,  4,  3,  0,  6,  6,  8,  3,  6,  4,  0,  2,  5,  9, -1,
       10, 11,  6, 10,  9, 11, 10,  1, 11,  6,  7,  6, -1,  3, 10,  1, 11,
        6, 10, 11,  1, -1,  6,  1,  1,  4, -1,  1,  3,  1, 11, 10,  6,  2,
        4,  5,  6, -1, -1,  3, 10,  1,  6,  1,  1,  5, 14,  1,  6, -1, -1,
        6, -1,  6,  6,  1,  4,  6,  4,  0,  2,  3,  2,  1,  1,  6,  0, 10,
        4,  6,  9, 10,  2,  6,  5, 14,  0,  1,  3, 12, 11,  9,  3, -1,  6,
       10,  0,  6, 10,  7, 12,  2,  2,  9,  1, 10, -1,  6,  6,  6,  6,  3,
       10, 11, 12,  3,  4, 10, -1, 10,  6,  4,  1,  9,  3,  6,  1,  5,  3,
        6,  1,  2,  4, 10, -1, 11,  4,  4,  2,  3,  6, -1, -1,  6, 12,  1,
        4, -1,  1, 11, 11,  2,  2, 10,  6,  3,  0,  6, -1,  5,  7,  6,  4,
       12,  2,  9,  7,  6,  3,  2,  7,  3,  3,  3,  4, -1, 11, 13,  3,  6,
        3,  0,  2, -1,  4, 13,  6,  6,  4,  3, 12,  4,  9,  7,  3,  1,  2,
        9,  8,  3,  7, 13

In [31]:
dbscan.core_sample_indices_

array([  0,   1,   2,   5,   6,   7,   8,   9,  10,  11,  12,  13,  15,
        17,  18,  19,  21,  22,  23,  24,  25,  26,  27,  28,  30,  31,
        32,  34,  35,  36,  37,  38,  39,  41,  42,  43,  44,  47,  48,
        49,  50,  51,  52,  53,  54,  56,  57,  58,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  73,  77,  81,  82,  85,  87,  88,  90,
        91,  92,  94,  95,  96,  97,  98, 100, 102, 103, 104, 105, 106,
       107, 108, 110, 111, 113, 114, 115, 116, 118, 119, 120, 121, 122,
       124, 125, 126, 127, 128, 129, 131, 132, 133, 134, 135, 136, 137,
       138, 139, 140, 141, 143, 144, 145, 146, 147, 148, 149, 152, 153,
       154, 156, 159, 160, 162, 163, 164, 167, 168, 169, 170, 172, 173,
       174, 175, 176, 177, 178, 179, 180, 181, 183, 184, 185, 186, 187,
       188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 201, 203, 204,
       205, 206, 208, 210, 212, 213, 214, 215, 216, 218, 219, 220, 221,
       222, 223, 224, 227, 228, 229, 230, 231, 232, 233, 234, 23

In [32]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=50)
knn.fit(dbscan.components_, dbscan.labels_[dbscan.core_sample_indices_])

,n_neighbors,50
,weights,'uniform'
,algorithm,'auto'
,leaf_size,30
,p,2
,metric,'minkowski'
,metric_params,None
,n_jobs,None


In [33]:
X_new = np.array([[-0.5, 0], [0, 0.5], [1, -0.1], [2, 1]])
knn.predict(X_new)


array([ 3, 10,  2,  1], dtype=int64)

In [34]:
y_dist, y_pred_idx = knn.kneighbors(X_new, n_neighbors=1)
y_pred = dbscan.labels_[dbscan.core_sample_indices_][y_pred_idx]
y_pred[y_dist > 0.2] = -1
y_pred.ravel()


array([-1, 10,  2, -1], dtype=int64)

In [35]:
from sklearn.mixture import GaussianMixture
gm = GaussianMixture(n_components=3, n_init=10)
gm.fit(X)

,n_components,3
,covariance_type,'full'
,tol,0.001
,reg_covar,1e-06
,max_iter,100
,n_init,10
,init_params,'kmeans'
,weights_init,None
,means_init,None
,precisions_init,None
,random_state,None


In [36]:
gm.weights_


array([0.20480978, 0.20448945, 0.59070077])

In [37]:
gm.means_

array([[-0.74084403,  0.56568568],
       [ 1.74246288, -0.05847579],
       [ 0.49333559,  0.24775503]])

In [38]:
gm.covariances_

array([[[ 0.05291913,  0.06118451],
        [ 0.06118451,  0.08786992]],

       [[ 0.05131935,  0.0602303 ],
        [ 0.0602303 ,  0.08570513]],

       [[ 0.17030738, -0.10215275],
        [-0.10215275,  0.28784075]]])